### ISSUE TITLE
Backtick not working on Windows

### ISSUE THREAD

**Issue by nueropath** [jrincayc/ucblogo-code#138]
Running the following command in ucbLogo 6.2.2 on windows,

```
print first (cascade 4 "bf [The Continuing Story of Bungalow Bill])
```

I get:
```
I don't know how  to `  in cascade
[if numberp :cascade.limit [if lessp :cascade.limit 0 [(throw "error (se [cascade doesn't like] :cascade.limit [as input] ))] make "cascade.limit ` [greaterp :template.number , [int :cascade.limit]]]]
```

while the expected output from CSLS is:
```
Bungalow
```

It seems this bug had occured before on MacOS #117.

**Comment by dmalec** [comment]
Interesting... I can replicate the behavior you are seeing with 6.2.2 on Windows. If I install 6.2 on Windows, it works as expected. The fix for the issue on MacOS shouldn't have impacted any other platform's builds, so I'm going to need to do a little digging into what caused the regression.

If you would like a workaround for 6.2.2 on Windows:
1. Go to the install folder (by default, this would be `C:\Program Files (x86)\UCBLogo`).
2. Open the `LOGOLIB` folder.
3. Rename the file `RENAME-GRAVE-ACCENT` to a literal backtick `` ` ``
4. Rename the file `RENAME-NUMBER-SIGN` to a literal number sign `#`

**Comment by nueropath** [comment]
> Interesting... I can replicate the behavior you are seeing with 6.2.2 on Windows. If I install 6.2 on Windows, it works as expected. The fix for the issue on MacOS shouldn't have impacted any other platforms' builds, so I'm going to need to do a little digging into what caused the regression.
> 
> If you would like a workaround for 6.2.2 on Windows:
> 
>     1. Go to the install folder (by default, this would be `C:\Program Files (x86)\UCBLogo`).
> 
>     2. Open the `LOGOLIB` folder.
> 
>     3. Rename the file `RENAME-GRAVE-ACCENT` to a literal backtick `` ` ``
> 
>     4. Rename the file `RENAME-NUMBER-SIGN` to a literal number sign `#`

much appericated for the workaround. It now works as expected.
