### ISSUE TITLE
seteditor command wont work .

### ISSUE THREAD

**Issue by aprekates** [jrincayc/ucblogo-code#31]
The building editor isnt helpfull since is lacking a visible cursor to me. 
I tried setting the editor  shell variable and using the seteditor command
but nothing change.

Alexandros

**Comment by jrincayc** [comment]
I thought I fixed the built-in editor not showing a cursor in version 6.1
Which version are you using? (If you compiled it yourself, what configure options did you use, if you used a pre-compiled version where did you get it?)  Any other hints to help me replicate this problem?
Thanks.

**Comment by aprekates** [comment]
?print logoversion
6
?print logoplatform
wxWidgets

I have Debian 10 :
$ sudo apt-cache show ucblogo
Package: ucblogo
Source: ucblogo (6.0+dfsg-2)
Version: 6.0+dfsg-2+b1

**Comment by jrincayc** [comment]
I see two bugs that are still in 6.1.
First of all 
seteditor seems to be broken.
Secondly,
edit actually still doesn't seem to have a working cursor in 6.1
I will look into both of those bugs, but it might be a bit till I have a chance to do so.  Thank you for reporting this.

There was another cursor bug that was in 6.0, but it was fixed in 6.1.  
It looks like ucblogo 6.1 is in bullseye and sid but not in buster (Debian 10)
The commit that fixed it is: https://github.com/jrincayc/ucblogo-code/commit/f666595457572d1152493594ab7ce2184bc1467f
I grant permission to use the changes in commit f666595 in the GPL2+ version of ucblogo if you or the Debian maintainer want to backport it.

**Comment by aprekates** [comment]
Thanks a lot for the quick response. Did you check also the 'editor' enviroment variable if working in 6.1 ?

**Comment by jrincayc** [comment]
EDITOR also doesn't work.

**Comment by aprekates** [comment]
Also i cant copy paste from the building editor. Again in version 6.
But i can paste to the editor. But only with text that i copied from another window.

**Comment by jrincayc** [comment]
Hm, there is actually a cursor in the editor, it is just thin and gray so it is really hard to see.

**Comment by jrincayc** [comment]
Alternatively, if you change the theme of gtk to white on black, then UCBLogo's white on black works.  Basically, wxGTK has a way to set the background and text color, but (so far as I can tell) not the text cursor color.
https://docs.wxwidgets.org/3.0/classwx_text_ctrl.html

**Comment by jrincayc** [comment]
I posted a question in the wxWidgets forum: https://forums.wxwidgets.org/viewtopic.php?f=1&t=47012

**Comment by jrincayc** [comment]
The wxWidgets repository has a fix for this.  I added a fix to set the foreground color. So on linux the hidden cursor can be fixed by compiling the newest wxWidgets and ucblogo:
```
git clone git@github.com:wxWidgets/wxWidgets.git
cd wxWidgets
git submodule update --init
mkdir build_gtk3
cd build_gtk3
../configure --with-gtk=3
make -j2
cd ucblogo
./configure --with-wx-config=$HOME/wxWidgets/build_gtk3/wx-config
make
```
I haven't closed this bug because the seteditor part still needs to be fixed.
