### ISSUE TITLE
Using STOP in macro causes crash

### ISSUE THREAD

**Issue by jasonsikes** [jrincayc/ucblogo-code#43]
When I type this:

.MACRO AA
STOP
END
AA

The application crashes. This occurs in both the MacOS and Windows versions. (My Fedora VM is broken so i can't test there right now.)

**Comment by brianharvey** [comment]
Well, crashing Logo is an extreme reaction on the part of the evaluator, but, just to make sure you know this, a macro is by definition an operation, not a command.  It has to output an instruction, so you might say
```
.macro aa
output [stop]
end
```
... and  even then, it would be an error to call that particular macro at toplevel, because STOP can be used only in a procedure.

But still, it shouldn't crash.  I'll look into it.
