### ISSUE TITLE
There should be a line-input version of KEYP

### ISSUE THREAD

**Issue by brianharvey** [jrincayc/ucblogo-code#69]
KEYP is defined to turn off echo and go into character-at-a-time input mode.  That's the right thing for the single-character-command sorts of user interfaces I was writing in Logo at the time, but today I want to be in line mode (so the user gets Unixy line editing ability) and still find out if there's a line ready to read.  So either it should have an optional input
(KEYP "LINE) or there should be a new LINEP predicate.

**Comment by dmalec** [comment]
I hadn't used the `KEYP` command before reading this. Thinking through this, I came up with the following to try and understand:
```
TO looper
  LOCALMAKE "ch "

  PENUP
  WHILE [NOT EQUALP "X :ch] [
    IF [KEYP] [
      MAKE "ch READCHAR
      LABEL :ch
    ]
    FD 2 RT 1
  ]
  PENDOWN
END
```
Where:
* The turtle is constantly moving in a circle until `X` is pressed.
* Whenever another key is pressed, the turtle draws the appropriate character.
* No keypresses are displayed in the terminal

My understanding of the new feature is that if you changed the above so that:
* `KEYP` -> `LINEP`
* `READCHAR` -> `READWORD` 

The behavior would be:
* The turtle is constantly moving in a circle until `X` is entered alone on a line.
* Keypresses work as they would in a typical invocation of `READWORD`, displaying to terminal and allowing for editing. 
* When a line is entered, the turtle draws the contents of the line.

Does this sound like I'm broadly headed in the right direction of how to think about it?

**Comment by brianharvey** [comment]
Yes, exactly.
